apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/shopping-cart-dynamodb-role
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart-api
  template:
    metadata:
      labels:
        app: shopping-cart-api
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/shopping-cart-dynamodb-role
    spec:
      serviceAccountName: shopping-cart-sa
      containers:
        - name: shopping-cart-api
          image: your-ecr-repo/shopping-cart-api:latest
          ports:
            - containerPort: 3008
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-secrets
                  key: jwt-secret
            - name: AWS_REGION
              value: 'ap-northeast-2'
            - name: DYNAMODB_TABLE_NAME
              value: 'hama-shopping-cart'
            - name: PORT
              value: '3008'
